# Generated by Django 5.0 on 2024-07-19 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfollows",
            options={
                "verbose_name": "User Follow",
                "verbose_name_plural": "User Follows",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userfollows",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="userfollows",
            constraint=models.UniqueConstraint(
                fields=("user", "followed_user"), name="unique_user_follow"
            ),
        ),
    ]
